# Generated by Django 6.0.5 on 2026-05-23 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_football_id', models.IntegerField(unique=True)),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('goles_local', models.IntegerField(blank=True, null=True)),
                ('goles_visitante', models.IntegerField(blank=True, null=True)),
                ('resultado_partido', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoApuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('multiplicador', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_apostado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prediccion', models.CharField(max_length=100)),
                ('cuota_aplicada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ganada', 'Ganada'), ('perdida', 'Perdida')], default='pendiente', max_length=100)),
                ('ganancia_cliente', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ganancia_casa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resultado_apuesta', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuesta.partido')),
                ('tipo_apuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuesta.tipoapuesta')),
            ],
        ),
    ]
