# Generated by Django 6.0.5 on 2026-05-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_apostado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota_aplicada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ganada', 'Ganada'), ('perdida', 'Perdida')], default='pendiente', max_length=100)),
                ('ganancia_cliente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ganancia_casa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionApuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_apuesta', models.CharField(choices=[('resultado', 'Resultado'), ('cantidad_goles', 'Cantidad de goles')], max_length=100)),
                ('prediccion', models.CharField(blank=True, choices=[('gana_local', 'Gana Local'), ('empate', 'Empate'), ('gana_visitante', 'Gana Visitante'), ('mas_1_gol', 'Más de 1 gol'), ('mas_3_goles', 'Más de 3 goles'), ('mas_5_goles', 'Más de 5 goles')], max_length=100, null=True)),
                ('multiplicador', models.DecimalField(decimal_places=2, max_digits=2)),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_football_id', models.IntegerField(unique=True)),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('goles_local', models.IntegerField(null=True)),
                ('goles_visitante', models.IntegerField(null=True)),
                ('resultado_partido', models.CharField(choices=[('L', 'Gana Local'), ('E', 'Empate'), ('V', 'Gana Visitante'), ('C', 'El partido se canceló por algún motivo externo')], max_length=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Partido',
            },
        ),
    ]
