# Generated by Django 6.0.5 on 2026-05-30 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apuesta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='apostado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='opcion_apuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuesta.opcionapuesta'),
        ),
        migrations.AddField(
            model_name='opcionapuesta',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuesta.partido'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuesta.partido'),
        ),
    ]
