# Generated by Django 6.0.5 on 2026-05-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_local',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_visitante',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultado_partido',
            field=models.CharField(choices=[('gano_local', 'Ganó el equipo local'), ('gano_visitante', 'Ganó el equipo visitante'), ('empate', 'El partido termino en empate')], max_length=30),
        ),
    ]
