# Generated by Django 6.0.5 on 2026-05-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionapuesta',
            name='prediccion',
            field=models.CharField(blank=True, choices=[('L', 'Gana Local'), ('E', 'Empate'), ('V', 'Gana Visitante'), ('mas_1_gol', 'Más de 1 gol'), ('mas_3_goles', 'Más de 3 goles'), ('mas_5_goles', 'Más de 5 goles')], max_length=100, null=True),
        ),
        migrations.AlterConstraint(
            model_name='opcionapuesta',
            name='unique_opcion_apuesta_partido',
            constraint=models.UniqueConstraint(fields=('partido', 'tipo_apuesta', 'prediccion'), name='unique_opcion_apuesta_partido', violation_error_message='Ya existe una opción de apuesta con esa predicción para este partido.'),
        ),
    ]
