# Generated by Django 6.0.5 on 2026-05-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apuesta',
            name='partido',
        ),
    ]
