# Generated by Django 6.0.5 on 2026-05-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0002_alter_partido_fecha_alter_partido_goles_local_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={'verbose_name': 'Partido'},
        ),
    ]
