# Generated by Django 6.0.5 on 2026-05-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionapuesta',
            name='monto_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opcionapuesta',
            name='multiplicador',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
