# Generated by Django 6.0.5 on 2026-05-30 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0003_remove_apuesta_partido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionapuesta',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_apuesta', to='apuesta.partido'),
        ),
    ]
