# Generated by Django 6.0.5 on 2026-05-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0003_alter_opcionapuesta_monto_minimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apuesta',
            name='cuota_aplicada',
        ),
    ]
