# Generated by Django 6.0.5 on 2026-05-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0003_alter_partido_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='resultado_partido',
            field=models.CharField(choices=[('L', 'Gana Local'), ('E', 'Empate'), ('V', 'Gana Visitante'), ('C', 'El partido se canceló por algún motivo externo')], max_length=1),
        ),
    ]
