# Generated by Django 6.0.5 on 2026-05-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0004_remove_apuesta_cuota_aplicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionapuesta',
            name='prediccion',
            field=models.CharField(blank=True, choices=[('L', 'Gana Local'), ('E', 'Empate'), ('v', 'Gana Visitante'), ('mas_1_gol', 'Más de 1 gol'), ('mas_3_goles', 'Más de 3 goles'), ('mas_5_goles', 'Más de 5 goles')], max_length=100, null=True),
        ),
    ]
