# Generated by Django 6.0.5 on 2026-05-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0004_alter_partido_resultado_partido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apuesta',
            name='resultado_apuesta',
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
