# Generated by Django 6.0.5 on 2026-05-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0005_remove_apuesta_resultado_apuesta_alter_apuesta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='tipo_apuesta',
            field=models.CharField(choices=[('resultado', 'Resultado'), ('cantidad de goles', 'Cantidad de goles'), ('ambos marcan', 'Ambos marcan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='cuota_aplicada',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='ganancia_casa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='ganancia_cliente',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='monto_apostado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='prediccion',
            field=models.CharField(choices=[('gana_local', 'Gana Local'), ('empate', 'Empate'), ('gana_visitante', 'Gana Visitante'), ('mas_1_gol', 'Más de 1 gol'), ('mas_3_goles', 'Más de 3 goles'), ('mas_5_goles', 'Más de 5 goles'), ('ambos_si', 'Ambos marcan Sí'), ('ambos_no', 'Ambos marcan No')], max_length=100),
        ),
        migrations.DeleteModel(
            name='TipoApuesta',
        ),
    ]
