# Generated by Django 6.0.5 on 2026-05-27 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0006_alter_apuesta_tipo_apuesta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoApuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('multiplicador', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='apuesta',
            name='prediccion',
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='tipo_apuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuesta.tipoapuesta'),
        ),
    ]
