# Generated by Django 6.0.5 on 2026-05-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0007_tipoapuesta_remove_apuesta_prediccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='ganancia_casa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='ganancia_cliente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
