# Generated by Django 6.0.5 on 2026-05-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_de_cuenta',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
