# Generated by Django 6.0.5 on 2026-05-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_numero_de_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_de_cuenta',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
